FROM mcr.microsoft.com/powershell
ARG SC_VERSION
ARG SOLR_VERSION
COPY ./configuration/${SC_VERSION} /home/configuration
COPY ./scripts /home/scripts
USER root
# RUN apt-get update && apt-get -y install gnupg2
# RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
# RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
# RUN apt-get update && apt-get -y install mssql-tools unixodbc-dev
SHELL ["pwsh", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Invoke-WebRequest -Uri "https://downloads.apache.org/lucene/solr/$env:SOLR_VERSION/solr-$env:SOLR_VERSION.zip" -OutFile /tmp/solr.zip; \
	Expand-Archive /tmp/solr.zip -DestinationPath /tmp; \
	Remove-Item /tmp/solr.zip -Force; \
	New-Item -Path /tmp/solr -Value /tmp/solr-$env:SOLR_VERSION -ItemType SymbolicLink
WORKDIR /home
CMD ["/home/scripts/Startup.ps1"]