apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - name: solr
        image: solr:7
        env:
        - name: ZK_HOST
          value: "zookeeper.default.svc.cluster.local:2181"
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
        ports:
        - containerPort: 8983