apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - name: solr
          image: george.azurecr.io/solr:7-1903
          resources:
            limits:
              memory: 512Mi
              cpu: 200m
          ports:
            - containerPort: 8983
