apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mssql/