apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard