version: "3.7"
services:
  mssql:
    image: ${REGISTRY}mssql:2017-RTM-${WIN_VERSION}
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
      - ATTACH_DBS=${SQL_DBS}
    volumes:
      - C:/docker/mssql/data:C:/data

  solr:
    image: solr:${SOLR_VERSION}-${WIN_VERSION}
    volumes:
      - C:/docker/solr:C:/solr/server/solr/mydata

  sitecore:
    image: ${REGISTRY}sitecore:${SC_VERSION}-${WIN_VERSION}
    depends_on:
      - mssql
      - solr
      - identity
      - xconnect
    ports:
      - "2222:80"
    environment:
      - SC_CONNSTRING_CORE=${SC_CONNSTRING_CORE}
      - SC_CONNSTRING_SECURITY=${SC_CONNSTRING_SECURITY}
      - SC_CONNSTRING_MASTER=${SC_CONNSTRING_MASTER}
      - SC_CONNSTRING_WEB=${SC_CONNSTRING_WEB}
      - SC_CONNSTRING_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SC_CONNSTRING_MARKETINGAUTOMATION=${SC_CONNSTRING_MARKETINGAUTOMATION}
      - SC_CONNSTRING_REFERENCEDATA=${SC_CONNSTRING_REFERENCEDATA}
      - SC_CONNSTRING_PROC_POOLS=${SC_CONNSTRING_PROC_POOLS}
      - SC_CONNSTRING_PROC_TASKS=${SC_CONNSTRING_PROC_TASKS}
      - SC_CONNSTRING_FORMS=${SC_CONNSTRING_FORMS}
      - SC_CONNSTRING_REPORTING=${SC_CONNSTRING_REPORTING}
      - SC_PKGMGMT_URL=${SC_PKGMGMT_URL}
      - SC_DATAFOLDER=${SC_DATAFOLDER}
      - SC_SOLR_PREFIX=${SC_SOLR_PREFIX}
      - SC_DEBUG=${SC_DEBUG}
      - SC_CUSTOMERRORS=${SC_CUSTOMERRORS}
      - EXM_CONNSTRING_MASTER=${EXM_CONNSTRING_MASTER}
      - EXM_CRYPTO_KEY=${EXM_CRYPTO_KEY}
      - EXM_AUTH_KEY=${EXM_AUTH_KEY}
      - XC_URL=${XC_URL}
      - XC_CONNSTRING_CERT=${XC_CONNSTRING_CERT}
      - SOLR_URL=${SOLR_URL}
      - SI_URL=${SI_URL}
      - SI_CLIENT_SECRET=${SI_CLIENT_SECRET}
    volumes:
      - C:/docker/sitecore/logs:C:/inetpub/wwwroot/App_Data/logs
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license

  identity:
    image: identity:${SC_VERSION}-${WIN_VERSION}
    ports:
      - "3333:80"
    environment:
      - SI_CERT_THUMBPRINT=${SI_CERT_THUMBPRINT}
      - SI_CERT_STORE_LOCATION=${SI_CERT_STORE_LOCATION}
      - SI_CERT_STORE_NAME=${SI_CERT_STORE_NAME}
      - SC_MEMBERSHIP_CONN_STRING=${SC_CONNSTRING_MEMBERSHIP}
      - SC_CM_URL=${SC_CM_URL}
      - SI_CLIENT_SECRET=${SI_CLIENT_SECRET}
    volumes:
      - ${PATH_LICENSE}:C:/license

  xconnect:
    image: ${REGISTRY}xconnect:${SC_VERSION}-${WIN_VERSION}
    depends_on:
      - mssql
      - solr
    # ports:
    #   - "4444:80"
    environment:
      - SC_CONNSTRING_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SC_CONNSTRING_REPORTING=${SC_CONNSTRING_REPORTING}
      - SC_CONNSTRING_MARKETINGAUTOMATION=${SC_CONNSTRING_MARKETINGAUTOMATION}
      - SC_CONNSTRING_REFERENCEDATA=${SC_CONNSTRING_REFERENCEDATA}
      - SC_CONNSTRING_PROC_POOLS=${SC_CONNSTRING_PROC_POOLS}
      - SC_CONNSTRING_PROCENG_STORAGE=${SC_CONNSTRING_PROCENG_STORAGE}
      - SC_CONNSTRING_SHARDMAPMANAGER=${SC_CONNSTRING_SHARDMAPMANAGER}
      - XC_CERT_THUMBPRINT=${XC_CERT_THUMBPRINT}
      - XC_ALLOW_INVALID_CERT=${XC_ALLOW_INVALID_CERT}
      - SOLR_REQUIRE_HTTPS=${SOLR_REQUIRE_HTTPS}
      - SOLR_XDB_CORE_URL=${SOLR_XDB_CORE_URL}
    volumes:
      - C:/docker/xconnect/logs:C:/inetpub/wwwroot/App_Data/logs
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license

  xconnect-indexworker:
    image: ${REGISTRY}xconnect.indexworker:${SC_VERSION}-${WIN_VERSION}
    depends_on:
      - mssql
      - solr
    environment:
      - SC_CONNSTRING_SHARDMAPMANAGER=${SC_CONNSTRING_SHARDMAPMANAGER}
      - SOLR_XDB_CORE_URL=${SOLR_XDB_CORE_URL}
      - SOLR_REQUIRE_HTTPS=${SOLR_REQUIRE_HTTPS}
    volumes:
      - ${PATH_LICENSE}:C:/license

  xconnect-maengine:
    image: ${REGISTRY}xconnect.maengine:${SC_VERSION}-${WIN_VERSION}
    depends_on:
      - mssql
      - solr
      - xconnect
    environment:
      - SC_CONNSTRING_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SC_CONNSTRING_MARKETINGAUTOMATION=${SC_CONNSTRING_MARKETINGAUTOMATION}
      - SC_CONNSTRING_REFERENCEDATA=${SC_CONNSTRING_REFERENCEDATA}
      - XC_URL=${XC_URL}
      - XC_CONNSTRING_CERT=${XC_CONNSTRING_CERT}
      - XC_ALLOW_INVALID_CERT=${XC_ALLOW_INVALID_CERT}
    volumes:
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license

  xconnect-processingengine:
    image: ${REGISTRY}xconnect.processingengine:${SC_VERSION}-${WIN_VERSION}
    depends_on:
      - mssql
      - solr
      - xconnect
    environment:
      - SC_CONNSTRING_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SC_CONNSTRING_REPORTING=${SC_CONNSTRING_REPORTING}
      - SC_CONNSTRING_PROCENG_STORAGE=${SC_CONNSTRING_PROCENG_STORAGE}
      - SC_CONNSTRING_PROCENG_TASKS=${SC_CONNSTRING_PROCENG_TASKS}
      - XC_URL=${XC_URL}
      - XC_CERT_THUMBPRINT=${XC_CERT_THUMBPRINT}
      - XC_ALLOW_INVALID_CERT=${XC_ALLOW_INVALID_CERT}
    volumes:
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license
