version: "3.7"
services:
  mssql:
    image: ${REGISTRY}mssql:2019-CU4-${WIN_VERSION}
    #image: microsoft/mssql-server-windows-developer:2017
    isolation: process
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
      - ATTACH_DBS=${SQL_DBS}
    volumes:
      - C:/docker/mssql/data:C:/data

  solr:
    image: solr:${SOLR_VERSION}-${WIN_VERSION}
    isolation: process
    volumes:
      - C:/docker/solr:C:/solr/server/solr/mydata

  sitecore:
    image: ${REGISTRY}sitecore:${SC_VERSION}-${WIN_VERSION}
    isolation: process
    depends_on:
      - mssql
      - solr
      # - identity
      - xconnect
    ports:
      - "2222:80"
    environment:
      - SITECORE_CONNECTIONSTRINGS_CORE=${SC_CONNSTRING_CORE}
      - SITECORE_CONNECTIONSTRINGS_SECURITY=${SC_CONNSTRING_SECURITY}
      - SITECORE_CONNECTIONSTRINGS_MASTER=${SC_CONNSTRING_MASTER}
      - SITECORE_CONNECTIONSTRINGS_WEB=${SC_CONNSTRING_WEB}
      - SITECORE_CONNECTIONSTRINGS_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION=${SC_CONNSTRING_MARKETINGAUTOMATION}
      - SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA=${SC_CONNSTRING_REFERENCEDATA}
      - SITECORE_CONNECTIONSTRINGS_XDB.PROCESSING.POOLS=${SC_CONNSTRING_PROC_POOLS}
      - SITECORE_CONNECTIONSTRINGS_XDB.PROCESSING.TASKS=${SC_CONNSTRING_PROC_TASKS}
      - SITECORE_CONNECTIONSTRINGS_EXPERIENCEFORMS=${SC_CONNSTRING_FORMS}
      - SITECORE_CONNECTIONSTRINGS_REPORTING=${SC_CONNSTRING_REPORTING}
      - SITECORE_CONNECTIONSTRINGS_SITECORE.REPORTING.CLIENT=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_SITECORE.REPORTING.CLIENT.CERTIFICATE=${XC_CONNSTRING_CERT}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION.CERTIFICATE=${XC_CONNSTRING_CERT}
      - SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION.OPERATIONS.CLIENT=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION.OPERATIONS.CLIENT.CERTIFICATE=${XC_CONNSTRING_CERT}
      - SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION.REPORTING.CLIENT=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION.REPORTING.CLIENT.CERTIFICATE=${XC_CONNSTRING_CERT}
      - SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA.CLIENT=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA.CLIENT.CERTIFICATE=${XC_CONNSTRING_CERT}
      - SITECORE_CONNECTIONSTRINGS_SITECOREIDENTITY.SECRET=${SI_CLIENT_SECRET}
      - SITECORE_CONNECTIONSTRINGS_EXM.MASTER=${EXM_CONNSTRING_MASTER}
      - SITECORE_CONNECTIONSTRINGS_EXM.CRYPTOGRAPHICKEY=${EXM_CRYPTO_KEY}
      - SITECORE_CONNECTIONSTRINGS_EXM.AUTHENTICATIONKEY=${EXM_AUTH_KEY}
      - SITECORE_CONNECTIONSTRINGS_SOLR.SEARCH=${SOLR_URL}
      - SITECORE_CONNECTIONSTRINGS_PACKAGEMANAGEMENTSERVICEURL=${SC_PKGMGMT_URL}
      - SC_DATAFOLDER=${SC_DATAFOLDER}
      - SC_SOLR_PREFIX=${SC_SOLR_PREFIX}
      - SC_DEBUG=${SC_DEBUG}
      - SC_CUSTOMERRORS=${SC_CUSTOMERRORS}
      - SI_URL=${SI_URL}

    volumes:
      - C:/docker/sitecore/logs:C:/inetpub/wwwroot/App_Data/logs
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license

  # identity:
  #   image: identity:${SC_VERSION}-${WIN_VERSION}
  #   isolation: process
  #   ports:
  #     - "3333:80"
  #   environment:
  #     - SI_CERT_THUMBPRINT=${SI_CERT_THUMBPRINT}
  #     - SI_CERT_STORE_LOCATION=${SI_CERT_STORE_LOCATION}
  #     - SI_CERT_STORE_NAME=${SI_CERT_STORE_NAME}
  #     - SC_MEMBERSHIP_CONN_STRING=${SC_CONNSTRING_MEMBERSHIP}
  #     - SC_CM_URL=${SC_CM_URL}
  #     - SI_CLIENT_SECRET=${SI_CLIENT_SECRET}
  #   volumes:
  #     - ${PATH_LICENSE}:C:/license

  xconnect:
    image: ${REGISTRY}xconnect:${SC_VERSION}-${WIN_VERSION}
    isolation: process
    depends_on:
      - mssql
      - solr
    # ports:
    #   - "4444:80"
    environment:
      - SITECORE_CONNECTIONSTRINGS_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SITECORE_CONNECTIONSTRINGS_REPORTING=${SC_CONNSTRING_REPORTING}
      - SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION=${SC_CONNSTRING_MARKETINGAUTOMATION}
      - SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA=${SC_CONNSTRING_REFERENCEDATA}
      - SITECORE_CONNECTIONSTRINGS_XDB.PROCESSING.POOLS=${SC_CONNSTRING_PROC_POOLS}
      - SITECORE_CONNECTIONSTRINGS_PROCESSING.ENGINE.STORAGE=${SC_CONNSTRING_PROCENG_STORAGE}
      - SITECORE_CONNECTIONSTRINGS_COLLECTION=${SC_CONNSTRING_SHARDMAPMANAGER}
      - SITECORE_CONNECTIONSTRINGS_SOLRCORE=${SOLR_XDB_CORE_URL}
      - XC_CERT_THUMBPRINT=${XC_CERT_THUMBPRINT}
      - XC_ALLOW_INVALID_CERT=${XC_ALLOW_INVALID_CERT}
      - SOLR_REQUIRE_HTTPS=${SOLR_REQUIRE_HTTPS}
    volumes:
      - C:/docker/xconnect/logs:C:/inetpub/wwwroot/App_Data/logs
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license

  xconnect-indexworker:
    image: ${REGISTRY}xconnect.indexworker:${SC_VERSION}-${WIN_VERSION}
    isolation: process
    depends_on:
      - mssql
      - solr
    environment:
      - SITECORE_CONNECTIONSTRINGS_COLLECTION=${SC_CONNSTRING_SHARDMAPMANAGER}
      - SITECORE_CONNECTIONSTRINGS_SOLRCORE=${SOLR_XDB_CORE_URL}
      - SOLR_REQUIRE_HTTPS=${SOLR_REQUIRE_HTTPS}
    volumes:
      - ${PATH_LICENSE}:C:/license

  xconnect-maengine:
    image: ${REGISTRY}xconnect.maengine:${SC_VERSION}-${WIN_VERSION}
    isolation: process
    depends_on:
      - mssql
      - solr
      - xconnect
    environment:
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION.CERTIFICATE=${XC_CONNSTRING_CERT}
      - SITECORE_CONNECTIONSTRINGS_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SITECORE_CONNECTIONSTRINGS_XDB.MARKETINGAUTOMATION=${SC_CONNSTRING_MARKETINGAUTOMATION}
      - SITECORE_CONNECTIONSTRINGS_XDB.REFERENCEDATA=${SC_CONNSTRING_REFERENCEDATA}
      - XC_ALLOW_INVALID_CERT=${XC_ALLOW_INVALID_CERT}
    volumes:
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license

  xconnect-processingengine:
    image: ${REGISTRY}xconnect.processingengine:${SC_VERSION}-${WIN_VERSION}
    isolation: process
    depends_on:
      - mssql
      - solr
      - xconnect
    environment:
      - SITECORE_CONNECTIONSTRINGS_MESSAGING=${SC_CONNSTRING_MESSAGING}
      - SITECORE_CONNECTIONSTRINGS_REPORTING=${SC_CONNSTRING_REPORTING}
      - SITECORE_CONNECTIONSTRINGS_PROCESSING.ENGINE.STORAGE=${SC_CONNSTRING_PROCENG_STORAGE}
      - SITECORE_CONNECTIONSTRINGS_PROCESSING.ENGINE.TASKS=${SC_CONNSTRING_PROCENG_TASKS}
      - SITECORE_CONNECTIONSTRINGS_PROCESSING.WEBAPI.BLOB=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_PROCESSING.WEBAPI.TABLE=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.COLLECTION.CERTIFICATE=${XC_CERT_THUMBPRINT}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.CONFIGURATION=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.CONFIGURATION.CERTIFICATE=${XC_CERT_THUMBPRINT}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.SEARCH=${XC_URL}
      - SITECORE_CONNECTIONSTRINGS_XCONNECT.SEARCH.CERTIFICATE=${XC_CERT_THUMBPRINT}
      - XC_ALLOW_INVALID_CERT=${XC_ALLOW_INVALID_CERT}
    volumes:
      - C:/docker/certificates:C:/certificates
      - ${PATH_LICENSE}:C:/license
