version: "3.7"
services:
  mssql:
    image: ${REGISTRY}mssql:2017-RTM-${WIN_VERSION}
    isolation: process
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
      - ATTACH_DBS=[]
    volumes:
      - ${PATH_DATA}/mssql/data:C:/data

  solr:
    image: solr:${SOLR_VERSION}-${WIN_VERSION}
    isolation: process
    volumes:
      - ${PATH_DATA}/solr:C:/solr/server/solr/mydata

  installer:
    image: builder:${SC_VERSION}-${WIN_VERSION}
    isolation: process
    depends_on:
      - mssql
      - solr
    environment:
      - DATABASE_PREFIX=sc_
      - DATABASE_SERVER=mssql
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=${SQL_SA_PASSWORD}
    command: "pwsh.exe /utilities/Installer.ps1"
